[theme]
base = "light"
primaryColor = "#10B981"            # verde jade
backgroundColor = "#FAFEFD"         # casi blanco con tinte verde
secondaryBackgroundColor = "#ECFDF5" # mint muy suave
textColor = "#0B1320"               # azul pizarra muy oscuro
font = "sans serif"
